### ISSUE TITLE
Etapa 1 Issue for everybody

### ISSUE THREAD

**Issue by serbanb17** [tipfoodshare/thesite#4]
_**15 Referirea și descrierea în text a fiecărei figuri/diagrame**_

**Comment by serbanb17** [comment]
Baza de date conține 3 tabele: USERS, PRODUCTS și ORDERS. În tabela USERS vor fi stocate datele tuturor utilizatorilor înregistrați. În tabela PRODUCTS vor fi stocate datele produselor publicate pe site. Ea va fi legată de utilizatori prin coloana PRODUCER, În tabela ORDERS vor fi stocate comenzile efectuate pe site. Această tabelă este legată de USERS prin coloana USER și de PRODUCTS prin coloana PRODUCT. Toate tablele au ca și index o cheie primară ID care este unică.

**Comment by simonamona** [comment]
[TI-P_etapa1.pdf](https://github.com/tipfoodshare/thesite/files/1862714/TI-P_etapa1.pdf)
